{% set version = '1.2.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-opera
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/opera_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/opera/opera_{{ version }}.tar.gz
  sha256: d066d7f03ea6bacf39471165cb2656ae168a9747cae770932bc20e4f0e03f025

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ posix }}make
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
    - r-rcppeigen
    - r-rdpack
    - r-alabama
    - r-htmltools
    - r-htmlwidgets
    - r-piper
    - r-ramcharts
  run:
    - r-base
    - r-rcpp
    - r-rcppeigen
    - r-rdpack
    - r-alabama
    - r-htmltools
    - r-htmlwidgets
    - r-piper
    - r-ramcharts

test:
  commands:
    - $R -e "library('opera')"           # [not win]

about:
  home: http://pierre.gaillard.me/opera.html
  license: LGPL-2.0-or-later
  summary: Misc methods to form online predictions, for regression-oriented time-series, by combining
    a finite set of forecasts provided by the user. See Cesa-Bianchi and Lugosi (2006)
    <doi:10.1017/CBO9780511546921> for an overview.
  license_family: LGPL
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3'

extra:
  recipe-maintainers:
    - SulphurFH

# Package: opera
# Type: Package
# Title: Online Prediction by Expert Aggregation
# Version: 1.2.0
# Author: Pierre Gaillard [cre, aut], Yannig Goude [aut], Laurent Plagne [ctb], Thibaut Dubois [ctb], Benoit Thieurmel [ctb]
# Maintainer: Pierre Gaillard <pierre@gaillard.me>
# Copyright: EDF R&D 2012-2015
# Description: Misc methods to form online predictions, for regression-oriented time-series, by combining a finite set of forecasts provided by the user. See Cesa-Bianchi and Lugosi (2006) <doi:10.1017/CBO9780511546921> for an overview.
# License: LGPL
# URL: http://pierre.gaillard.me/opera.html
# BugReports: https://github.com/dralliag/opera/issues
# Depends: R (>= 3.5.0)
# LinkingTo: Rcpp, RcppEigen
# Imports: Rcpp, htmltools, rAmCharts, htmlwidgets, pipeR, alabama, methods, Rdpack
# Suggests: quantreg, quadprog, RColorBrewer, testthat, splines, caret, mgcv, survival, knitr, gbm, rmarkdown, magrittr
# RdMacros: Rdpack
# LazyData: true
# VignetteBuilder: knitr
# RoxygenNote: 7.1.2
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2021-12-06 17:07:44 UTC; BenoitThieurmel
# Repository: CRAN
# Date/Publication: 2021-12-06 18:00:02 UTC
